name: panna_assets
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  supabase_flutter: ^1.4.0
  file_picker: ^4.6.1


  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/arsenal.png
      - assets/bournemouth.png
      - assets/brentford.png
      - assets/brighton.png
      - assets/chelsea.png
      - assets/everton.png
      - assets/forest.png
      - assets/fulham.png
      - assets/ipswich.png
      - assets/leicester.png
      - assets/liverpool.png
      - assets/man city.png
      - assets/man united.png
      - assets/newcastle.png
      - assets/palace.png
      - assets/southampton.png
      - assets/tottenham.png
      - assets/villa.png
      - assets/west ham.png
      - assets/wolves.png
